[package]
name = "bench_wasm_zero"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm_zero = { path = "../../crates/wasm_zero" }
rkyv = { version = "0.8", default-features = false, features = ["alloc", "pointer_width_32", "bytecheck"] }
dlmalloc = { version = "0.2", features = ["global"] }
