//! Build-helper for `wasm_zero`.
//!
//! `wasm_zero` is split into two halves that run at different points in the
//! build:
//!
//! ```text
//! wasm_zero_macro   (proc macro)  -> runs inside rustc, emits the FFI shim
//! wasm_zero_build   (this crate)  -> runs in build.rs, emits the .ts bindings
//! ```
//!
//! A proc macro can only hand a `TokenStream` back to the compiler — it cannot
//! write files to the workspace. `build.rs`, on the other hand, runs *before*
//! rustc and is free to read source files and write artifacts. So the
//! TypeScript bindings that mirror each `#[wasm_zero]` function are produced
//! here.
//!
//! Typical usage from a consumer crate's `build.rs`:
//!
//! ```no_run
//! fn main() {
//!     wasm_zero_build::generate("src/lib.rs", "pkg/bindings.ts");
//! }
//! ```
//!
//! This is the same split `prost` / `prost-build`, `uniffi`, and
//! `wasm-bindgen` use: the macro transforms code at compile time, the build
//! helper generates the sidecar artifact.

use std::path::Path;

use syn::{Item, ItemFn, ItemStruct, ReturnType, Type};

/// The runtime module the generated bindings import their helpers from.
///
/// The emitted `.ts` assumes a hand-written (or separately generated) runtime
/// that exposes the loaded wasm instance plus the marshalling helpers. Adjust
/// the import in the generated file if your runtime lives elsewhere.
const RUNTIME_MODULE: &str = "./runtime";

/// Scan `src` for `#[wasm_zero]` functions and write the TypeScript bindings to
/// `out`, creating parent directories as needed.
///
/// Intended to be called from a `build.rs`. Emits the appropriate
/// `cargo:rerun-if-changed` line so the bindings are regenerated whenever the
/// source changes. Panics (failing the build) if the source cannot be read or
/// parsed, or the output cannot be written — a build script has no better
/// recovery than to surface the error.
pub fn generate(src: impl AsRef<Path>, out: impl AsRef<Path>) {
    let src = src.as_ref();
    let out = out.as_ref();

    let source = std::fs::read_to_string(src).unwrap_or_else(|e| {
        panic!("wasm_zero_build: failed to read {}: {e}", src.display())
    });

    let bindings = generate_bindings(&source).unwrap_or_else(|e| {
        panic!("wasm_zero_build: failed to parse {}: {e}", src.display())
    });

    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent).unwrap_or_else(|e| {
            panic!(
                "wasm_zero_build: failed to create {}: {e}",
                parent.display()
            )
        });
    }

    std::fs::write(out, bindings).unwrap_or_else(|e| {
        panic!("wasm_zero_build: failed to write {}: {e}", out.display())
    });

    println!("cargo:rerun-if-changed={}", src.display());
}

/// Parse `source` and render the full TypeScript bindings file.
///
/// Pure (no I/O), so it can be unit-tested directly. Emits a TS `interface` for
/// every struct that derives `rkyv::Archive`, followed by an `async` wrapper
/// for every `#[wasm_zero]` function.
pub fn generate_bindings(source: &str) -> syn::Result<String> {
    let file = syn::parse_file(source)?;

    let mut out = String::new();
    out.push_str("// Auto-generated by wasm_zero. Do not edit by hand.\n");
    out.push_str(&format!(
        "import {{ wasm, malloc, free, deserialize, ErrorCode, WasmError, MAX_BUFFER_SIZE }} from \"{RUNTIME_MODULE}\";\n"
    ));

    for item in &file.items {
        if let Item::Struct(s) = item {
            if derives_archive(s) {
                out.push_str(&generate_ts_interface(s));
            }
        }
    }

    for item in &file.items {
        if let Item::Fn(f) = item {
            if has_wasm_zero_attr(f) {
                out.push_str(&generate_ts_function(f));
            }
        }
    }

    Ok(out)
}

/// True if the function carries the `#[wasm_zero]` attribute.
fn has_wasm_zero_attr(f: &ItemFn) -> bool {
    f.attrs.iter().any(|a| a.path().is_ident("wasm_zero"))
}

/// True if the struct has a `#[derive(...)]` that includes `Archive`, i.e. it is
/// an rkyv-serializable type that may appear as a `#[wasm_zero]` return value.
fn derives_archive(s: &ItemStruct) -> bool {
    s.attrs.iter().any(|attr| {
        if !attr.path().is_ident("derive") {
            return false;
        }
        let mut found = false;
        // `parse_nested_meta` walks each path in `#[derive(A, B, ...)]`.
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("Archive") {
                found = true;
            }
            Ok(())
        });
        found
    })
}

/// Render the `async` wrapper for one `#[wasm_zero]` function.
///
/// The wrapper mirrors the FFI shim emitted by `wasm_zero_macro`: it allocates a
/// `[len: u32][payload]` output buffer, invokes `__wasm_zero_<name>(outPtr)`,
/// checks the returned [`ErrorCode`], deserializes the payload, and always frees
/// the buffer.
///
/// Note: the current shim ABI takes no inputs beyond the output pointer, so the
/// generated wrappers are nullary — matching the macro's generated signature.
fn generate_ts_function(f: &ItemFn) -> String {
    let name = f.sig.ident.to_string();
    let shim_name = format!("__wasm_zero_{name}");

    let ts_return = match &f.sig.output {
        ReturnType::Type(_, ty) => rust_type_to_ts(ty),
        ReturnType::Default => "void".to_string(),
    };

    format!(
        r#"
export async function {name}(): Promise<{ts_return}> {{
    const outPtr = malloc(4 + MAX_BUFFER_SIZE);
    try {{
        const errCode = wasm.{shim_name}(outPtr);
        if (errCode !== ErrorCode.Ok) throw new WasmError(errCode);
        return deserialize<{ts_return}>(outPtr);
    }} finally {{
        free(outPtr, 4 + MAX_BUFFER_SIZE);
    }}
}}
"#
    )
}

/// Render a TS `interface` mirroring an rkyv struct's public named fields.
///
/// Tuple structs and unit structs have no named fields to project, so they are
/// emitted as empty interfaces (the type name still needs to exist for return
/// types to resolve).
fn generate_ts_interface(s: &ItemStruct) -> String {
    let name = s.ident.to_string();

    let mut body = String::new();
    if let syn::Fields::Named(fields) = &s.fields {
        for field in &fields.named {
            // Unwrap is safe: `Fields::Named` guarantees every field is named.
            let field_name = field.ident.as_ref().unwrap().to_string();
            let ts_ty = rust_type_to_ts(&field.ty);
            body.push_str(&format!("    {field_name}: {ts_ty};\n"));
        }
    }

    format!("\nexport interface {name} {{\n{body}}}\n")
}

/// Map a Rust type to its TypeScript equivalent.
///
/// Handles the rkyv-friendly primitives, `String`/`&str`, `Vec<T>` → `T[]`,
/// `Option<T>` → `T | null`, and references (by recursing into the referent).
/// Unknown named types are passed through verbatim so they resolve against a
/// generated interface; anything else falls back to `unknown`.
fn rust_type_to_ts(ty: &Type) -> String {
    match ty {
        Type::Reference(r) => rust_type_to_ts(&r.elem),
        Type::Paren(p) => rust_type_to_ts(&p.elem),
        Type::Group(g) => rust_type_to_ts(&g.elem),
        Type::Slice(s) => format!("{}[]", rust_type_to_ts(&s.elem)),
        Type::Array(a) => format!("{}[]", rust_type_to_ts(&a.elem)),
        Type::Path(p) => {
            let Some(segment) = p.path.segments.last() else {
                return "unknown".to_string();
            };
            let ident = segment.ident.to_string();

            // Handle the single-generic containers by inspecting their argument.
            if let syn::PathArguments::AngleBracketed(args) = &segment.arguments {
                let inner = args.args.iter().find_map(|arg| match arg {
                    syn::GenericArgument::Type(t) => Some(t),
                    _ => None,
                });
                if let Some(inner) = inner {
                    match ident.as_str() {
                        "Vec" | "Box" => {
                            if ident == "Box" {
                                return rust_type_to_ts(inner);
                            }
                            return format!("{}[]", rust_type_to_ts(inner));
                        }
                        "Option" => {
                            return format!("{} | null", rust_type_to_ts(inner))
                        }
                        _ => {}
                    }
                }
            }

            match ident.as_str() {
                "u8" | "u16" | "u32" | "i8" | "i16" | "i32" | "f32" | "f64"
                | "usize" | "isize" => "number".to_string(),
                "u64" | "i64" | "u128" | "i128" => "bigint".to_string(),
                "bool" => "boolean".to_string(),
                "String" | "str" | "char" => "string".to_string(),
                // A user-defined type — assume a matching interface exists.
                other => other.to_string(),
            }
        }
        Type::Tuple(t) if t.elems.is_empty() => "void".to_string(),
        _ => "unknown".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_primitives() {
        assert_eq!(rust_type_to_ts(&syn::parse_quote!(u32)), "number");
        assert_eq!(rust_type_to_ts(&syn::parse_quote!(u64)), "bigint");
        assert_eq!(rust_type_to_ts(&syn::parse_quote!(bool)), "boolean");
        assert_eq!(rust_type_to_ts(&syn::parse_quote!(String)), "string");
        assert_eq!(rust_type_to_ts(&syn::parse_quote!(&str)), "string");
    }

    #[test]
    fn maps_containers() {
        assert_eq!(rust_type_to_ts(&syn::parse_quote!(Vec<u8>)), "number[]");
        assert_eq!(
            rust_type_to_ts(&syn::parse_quote!(Option<String>)),
            "string | null"
        );
        assert_eq!(rust_type_to_ts(&syn::parse_quote!(Person)), "Person");
    }

    #[test]
    fn generates_interface_and_function() {
        let src = r#"
            #[derive(Archive, Serialize, Deserialize)]
            pub struct Person { pub name: String, pub age: u32 }

            #[wasm_zero]
            pub fn get_adult_person() -> Person { todo!() }

            pub fn ignored() -> u32 { 0 }
        "#;

        let out = generate_bindings(src).unwrap();
        assert!(out.contains("export interface Person {"));
        assert!(out.contains("name: string;"));
        assert!(out.contains("age: number;"));
        assert!(out.contains(
            "export async function get_adult_person(): Promise<Person>"
        ));
        assert!(out.contains("wasm.__wasm_zero_get_adult_person(outPtr)"));
        // Functions without the attribute are not exported.
        assert!(!out.contains("function ignored"));
    }
}
