// Auto-generated by wasm_zero. Do not edit by hand.

export const ErrorCode = Object.freeze({ Ok: 0, UnarchivingError: 254, ArchivingError: 255 });

export class WasmError extends Error {
  constructor(code) {
    super(`wasm_zero call failed with ErrorCode ${code}`);
    this.name = 'WasmError';
    this.code = code;
  }
}

export const MAX_BUFFER_SIZE = 512 * 1024;
const HEADER = 16; // archive offset; must match wasm_zero::mem::HEADER

// ---- zero-copy readers (read straight from wasm memory) ----
const __td = new TextDecoder();
function rdStr(dv, u8, a) {
  if ((u8[a] & 0xc0) !== 0x80) { // inline (SSO)
    let n = 0; while (n < 8 && u8[a + n] !== 0xff) n++;
    return __td.decode(u8.subarray(a, a + n));
  }
  const raw = dv.getUint32(a, true);
  const len = (raw & 0x3f) | ((raw & 0xffffff00) >>> 2);
  const off = dv.getInt32(a + 4, true);
  return __td.decode(u8.subarray(a + off, a + off + len));
}
function rdVec(dv, a, Ctor) { // zero-copy typed-array view
  const off = dv.getInt32(a, true), len = dv.getUint32(a + 4, true);
  return new Ctor(dv.buffer, a + off, len);
}
function rdVecOf(dv, u8, a, stride, rd) {
  const off = dv.getInt32(a, true), len = dv.getUint32(a + 4, true), b = a + off;
  const out = new Array(len);
  for (let i = 0; i < len; i++) out[i] = rd(b + i * stride);
  return out;
}

// ---- per-struct field readers ----
export function bindWasmZero(wasm: any) {
  const outPtr = wasm.malloc(HEADER + MAX_BUFFER_SIZE);
  let inPtr = 0; // lazily allocated for non-scalar args
  let buf = wasm.memory.buffer, dv = new DataView(buf), u8 = new Uint8Array(buf);
  function views() { if (buf !== wasm.memory.buffer) { buf = wasm.memory.buffer; dv = new DataView(buf); u8 = new Uint8Array(buf); } }

  function invoke(shim: string, argCodec: any, argValue: any, directArgs: any) {
    if (directArgs !== null) return wasm[shim](...directArgs, outPtr);
    if (argCodec === null) return wasm[shim](outPtr);
             throw new Error('unreachable: no non-scalar args');
           }

  // Run the shim, then read the result straight from wasm memory at the
  // archive root. Struct/vec results alias the scratch buffer — valid
  // until the next call (or memory.grow); copy if you need to keep them.
  function call(shim: string, size: number, read: any, argCodec: any, argValue: any, directArgs: any) {
    const code = invoke(shim, argCodec, argValue, directArgs);
    if (code !== ErrorCode.Ok) throw new WasmError(code);
    views();
    const len = dv.getUint32(outPtr, true);
    return read(dv, u8, outPtr + HEADER + len - size);
  }

  return {
    wasm,
    parallel_sum_squares(n: number): bigint { return wasm["__wasm_zero_parallel_sum_squares"](n); },
    parallel_count_primes(n: number): number { return wasm["__wasm_zero_parallel_count_primes"](n); },
  };
}

export async function initWasmZero(wasmUrl: string | URL, imports?: WebAssembly.Imports) {
  const importObject =
    imports ?? new Proxy({}, { get: () => new Proxy({}, { get: () => () => {} }) });
  const { instance } = await WebAssembly.instantiateStreaming(fetch(wasmUrl), importObject);
  return bindWasmZero(instance.exports);
}
