// Auto-generated by wasm_zero. Do not edit by hand.
import { wasm, malloc, free, deserialize, ErrorCode, WasmError, MAX_BUFFER_SIZE } from "./runtime";

export interface Person {
    name: string;
    age: number;
}

export async function get_adult_person(): Promise<Person> {
    const outPtr = malloc(4 + MAX_BUFFER_SIZE);
    try {
        const errCode = wasm.__wasm_zero_get_adult_person(outPtr);
        if (errCode !== ErrorCode.Ok) throw new WasmError(errCode);
        return deserialize<Person>(outPtr);
    } finally {
        free(outPtr, 4 + MAX_BUFFER_SIZE);
    }
}

export async function greet(): Promise<string> {
    const outPtr = malloc(4 + MAX_BUFFER_SIZE);
    try {
        const errCode = wasm.__wasm_zero_greet(outPtr);
        if (errCode !== ErrorCode.Ok) throw new WasmError(errCode);
        return deserialize<string>(outPtr);
    } finally {
        free(outPtr, 4 + MAX_BUFFER_SIZE);
    }
}
