// Auto-generated by wasm_zero. Do not edit by hand.
import * as r from 'rkyv-js';

export const ErrorCode = Object.freeze({ Ok: 0, UnarchivingError: 254, ArchivingError: 255 });

export class WasmError extends Error {
  constructor(code) {
    super(`wasm_zero call failed with ErrorCode ${code}`);
    this.name = 'WasmError';
    this.code = code;
  }
}

// Scratch buffer the shim writes its `[len][payload]` into.
export const MAX_BUFFER_SIZE = 64 * 1024;

// ---- codecs ----
export const ArchivedPerson = r.struct({
  name: r.string,
  age: r.u32,
  email: r.option(r.string),
  scores: r.vec(r.u32),
});

// ---- client ----
export function bindWasmZero(wasm) {
  function call(shim, codec) {
    const outPtr = wasm.malloc(4 + MAX_BUFFER_SIZE);
    try {
      const code = wasm[shim](outPtr);
      if (code !== ErrorCode.Ok) throw new WasmError(code);
      // Re-read memory after the call — malloc may have grown it.
      const view = new DataView(wasm.memory.buffer);
      const len = view.getUint32(outPtr, true);
      // Copy the archive out before freeing the scratch buffer.
      const bytes = new Uint8Array(wasm.memory.buffer, outPtr + 4, len).slice();
      return r.decode(codec, bytes);
    } finally {
      wasm.free(outPtr, 4 + MAX_BUFFER_SIZE);
    }
  }

  return {
    wasm,
    get_adult_person() { return call("__wasm_zero_get_adult_person", ArchivedPerson); },
    greet() { return call("__wasm_zero_greet", r.string); },
  };
}

export async function initWasmZero(wasmUrl, imports) {
  const importObject =
    imports ?? new Proxy({}, { get: () => new Proxy({}, { get: () => () => {} }) });
  const { instance } = await WebAssembly.instantiateStreaming(fetch(wasmUrl), importObject);
  return bindWasmZero(instance.exports);
}
